/**
 * Where the static corpus lives, and which build of it this deployment expects.
 *
 * The corpus is published as an immutable, versioned directory: a manifest and
 * a set of fixed-size chunks that are never rewritten in place. A deployment
 * points at one version; publishing the next one does not disturb a reader who
 * is midway through loading the previous, because the old paths still resolve.
 *
 * Two things follow from that and are load-bearing:
 *
 *   The manifest's own `urlPrefix` is relative. `sql.js-httpvfs` resolves it
 *   against the URL the manifest was fetched from, so moving the corpus from
 *   the site's own static assets to a separate data host is a change of one
 *   environment variable and no code. An absolute `/data/...` prefix would pin
 *   the chunks to the site origin no matter where the manifest came from.
 *
 *   The chunk count is never stated here. It is in the manifest, generated by
 *   scripts/chunk-db.mjs, and changing the chunk size must not require an
 *   application edit.
 */

import corpusMeta from '../data/corpus-meta.json';

/**
 * The corpus build this deployment serves.
 *
 * Generated by scripts/build-corpus-meta.mjs from the database the build was
 * cut from. `PUBLIC_CORPUS_VERSION` overrides it so a deployment can be pinned
 * to, or rolled back to, a version other than the one in the working tree.
 */
export const CORPUS_VERSION: string =
  import.meta.env.PUBLIC_CORPUS_VERSION || corpusMeta.corpusVersion;

/**
 * Where versioned corpus directories are served from.
 *
 * `/data/corpus/` is the dev server's own middleware, which answers ranges.
 * Any other build has to be told an absolute origin through
 * `PUBLIC_CORPUS_BASE_URL`, `https://data.hadithcriticblog.com/`. Must end in
 * a slash; the version is appended to it.
 */
const RAW_BASE: string = import.meta.env.PUBLIC_CORPUS_BASE_URL || '/data/corpus/';

/**
 * A built site may not fall back to serving the corpus from its own origin.
 *
 * This shipped, and every corpus page on the deployed site failed. Cloudflare
 * static assets answer a range request with `200` and the whole file, so the
 * site's own origin cannot serve the corpus at all: `openCorpus()` probes for
 * `206` and refuses, which is the right answer and a broken page. Nothing
 * before this point objected, and the first report came from a reader.
 *
 * The dev server is exempt because its middleware does answer `206`. Every
 * other build states the origin: scripts/build-for-e2e.mjs points at the test
 * corpus server, and a deployment points at R2. Failing the build is the only
 * moment left where this is cheap to notice.
 */
if (import.meta.env.PROD && !/^https?:\/\//.test(RAW_BASE)) {
  throw new Error(
    'PUBLIC_CORPUS_BASE_URL is not set, so this build would ask for the corpus ' +
      "from the site's own origin. Cloudflare static assets answer a range " +
      'request with 200 and the whole file, which the corpus cannot be read ' +
      'from. Set it to the origin serving the chunks, for example ' +
      'https://data.hadithcriticblog.com/, or use `npm run build:e2e`.'
  );
}

export const CORPUS_BASE_URL: string = RAW_BASE.endsWith('/') ? RAW_BASE : `${RAW_BASE}/`;

/** The versioned directory holding one build's manifest and chunks. */
export const CORPUS_DIR_URL = `${CORPUS_BASE_URL}${CORPUS_VERSION}/`;

/** The `jsonconfig` document `sql.js-httpvfs` is pointed at. */
export const CORPUS_MANIFEST_URL = `${CORPUS_DIR_URL}manifest.json`;

/** Emitted by sql.js-httpvfs's own build, copied into public/ verbatim. */
export const CORPUS_WORKER_URL = '/sqlite.worker.js';
export const CORPUS_WASM_URL = '/sql-wasm.wasm';

/**
 * A ceiling on how much of the corpus one page may pull down.
 *
 * `sql.js-httpvfs` throws once a session passes this. A pathological query, one
 * that walks the whole 1.6 GB file a page at a time, then becomes a caught
 * error and a readable message rather than a tab that quietly downloads for ten
 * minutes on someone's phone data. Generous enough that no normal search,
 * dossier or collection page comes close: the expensive shapes here measure in
 * single-digit megabytes.
 */
export const CORPUS_MAX_BYTES_PER_SESSION = 192 * 1024 * 1024;

/** Totals and lists generated from the corpus, for pages that must not query. */
export const CORPUS_META = corpusMeta;

/**
 * Which corpus build a page is actually serving, readable from the console.
 *
 * Worth the two lines: when a reader reports a narration that is missing or a
 * count that looks wrong, the first question is which version they were on, and
 * a deployment can be pinned to an older one with `PUBLIC_CORPUS_VERSION`.
 */
if (typeof window !== 'undefined') {
  const w = window as unknown as Record<string, unknown>;
  w.__corpusVersion = CORPUS_VERSION;
  w.__corpusManifest = CORPUS_MANIFEST_URL;
}
