/*
 * The hadith-criticism research graph: works, the scholars who wrote them, and the
 * relations between works. The data file is generated by scripts/research-graph and
 * committed, like corpus-meta.json. Nothing here grades a work or a scholar.
 */

export type EdgeType = 'cites' | 'part_of' | 'reviews' | 'replies_to';

export interface SiteLink {
  href: string;
  label: string;
  slug?: string;
}

export interface Work {
  id: string;
  title: string;
  publishedTitle?: string;
  year?: number;
  type?: string;
  venue?: string;
  publisher?: string;
  doi?: string;
  themes: string[];
  methods?: string[];
  site?: SiteLink[];
  authors: string[];
  role: 'author' | 'editor';
  openAccess: boolean;
  provenance: 'crossref+title-page' | 'title-page' | 'crossref+contents-page' | 'contents-page';
  unconfirmed?: string[];
  /** The atlas dates this work by a later edition; the first edition (often in another language) is described here. */
  originalYear?: number;
  originalNote?: string;
  /** The copy in the library is a later revision of the dated original, so it may cite newer work. */
  revisedCopy?: boolean;
}

export interface Scholar {
  id: string;
  name: string;
  works: string[];
  firstYear: number | null;
  lastYear: number | null;
}

export interface Edge {
  from: string;
  to: string;
  type: EdgeType;
  count?: number;
  /** For part_of: the printed page of the volume on which the study begins. */
  page?: number;
}

export interface GraphData {
  generated: string;
  note: string;
  works: Work[];
  scholars: Scholar[];
  edges: Edge[];
}

export interface GraphIndex {
  data: GraphData;
  workById: Map<string, Work>;
  scholarById: Map<string, Scholar>;
  /** Works this work cites inside the collection. */
  cites: Map<string, string[]>;
  /** Works in the collection that cite this work. */
  citedBy: Map<string, string[]>;
  /** The volume a chapter belongs to, when that volume is in the collection. */
  partOf: Map<string, string>;
  /** The studies printed inside a volume, in the order they begin. */
  parts: Map<string, string[]>;
  /** The printed page of the volume on which each study begins. */
  partPage: Map<string, number>;
}

/** Fails the build with a specific message when the data file is inconsistent. */
export function validateGraph(data: GraphData): void {
  const ids = new Set<string>();
  for (const work of data.works) {
    if (ids.has(work.id)) throw new Error(`research-graph: duplicate work id ${work.id}`);
    ids.add(work.id);
    if (!work.title || work.authors.length === 0) throw new Error(`research-graph: ${work.id} lacks a title or an author`);
  }
  const scholarIds = new Set(data.scholars.map((s) => s.id));
  for (const work of data.works) {
    for (const a of work.authors) if (!scholarIds.has(a)) throw new Error(`research-graph: ${work.id} names unknown scholar ${a}`);
  }
  for (const e of data.edges) {
    if (!ids.has(e.from) || !ids.has(e.to)) throw new Error(`research-graph: edge ${e.from} -> ${e.to} has an unknown endpoint`);
    if (e.from === e.to) throw new Error(`research-graph: self edge on ${e.from}`);
  }
}

function push(map: Map<string, string[]>, key: string, value: string): void {
  const list = map.get(key);
  if (list) list.push(value);
  else map.set(key, [value]);
}

export function indexGraph(data: GraphData): GraphIndex {
  validateGraph(data);
  const cites = new Map<string, string[]>();
  const citedBy = new Map<string, string[]>();
  const partOf = new Map<string, string>();
  const parts = new Map<string, string[]>();
  const partPage = new Map<string, number>();
  for (const e of data.edges) {
    if (e.type === 'cites') {
      push(cites, e.from, e.to);
      push(citedBy, e.to, e.from);
    } else if (e.type === 'part_of') {
      partOf.set(e.from, e.to);
      push(parts, e.to, e.from);
      if (e.page !== undefined) partPage.set(e.from, e.page);
    }
  }
  for (const ids of parts.values()) ids.sort((a, b) => (partPage.get(a) ?? 0) - (partPage.get(b) ?? 0));
  return {
    data,
    workById: new Map(data.works.map((w) => [w.id, w])),
    scholarById: new Map(data.scholars.map((s) => [s.id, s])),
    cites,
    citedBy,
    partOf,
    parts,
    partPage
  };
}

export function authorLine(work: Work, index: GraphIndex): string {
  const names = work.authors.map((id) => index.scholarById.get(id)?.name ?? id);
  const line = names.length > 2 ? `${names[0]} et al.` : names.join(' and ');
  return work.role === 'editor' ? `${line} (ed.)` : line;
}

export function venueLine(work: Work): string {
  return [work.venue, work.publisher].filter(Boolean).join(' · ');
}

/* ------------------------------------------------------------------ timeline layout */

export interface TimelineNode {
  id: string;
  x: number;
  y: number;
  row: number;
}

export interface Timeline {
  width: number;
  height: number;
  left: number;
  rows: { scholarId: string; name: string; y: number }[];
  ticks: { year: number; x: number }[];
  undatedX: number;
  nodes: TimelineNode[];
}

const ROW = 30;
const TOP = 34;
const LEFT = 150;
const RIGHT = 50;
const PLOT = 560;
const PIVOT = 1990;
const EARLY_SHARE = 0.2;

/**
 * One row per lead author, x by publication year. Works from the same author in the
 * same year sit side by side. Works with no printed year go in a final "n.d." column.
 */
export function layoutTimeline(index: GraphIndex): Timeline {
  const works = index.data.works;
  const years = works.map((w) => w.year).filter((y): y is number => typeof y === 'number');
  const min = Math.floor(Math.min(...years) / 10) * 10;
  const max = Math.ceil((Math.max(...years) + 1) / 10) * 10;
  /* Most of the literature is recent, so the scale widens at the pivot year. */
  const pivot = Math.max(min, PIVOT);
  const early = pivot > min ? EARLY_SHARE * PLOT : 0;
  const scale = (year: number) =>
    LEFT + (year < pivot ? ((year - min) / Math.max(1, pivot - min)) * early : early + ((year - pivot) / (max - pivot)) * (PLOT - early));
  const undatedX = LEFT + PLOT + 40;

  const lead = new Map<string, Work[]>();
  for (const w of works) {
    const list = lead.get(w.authors[0]) ?? [];
    list.push(w);
    lead.set(w.authors[0], list);
  }
  const order = [...lead.keys()].sort((a, b) => lead.get(b)!.length - lead.get(a)!.length || a.localeCompare(b));
  const rows = order.map((scholarId, i) => ({ scholarId, name: index.scholarById.get(scholarId)?.name ?? scholarId, y: TOP + i * ROW + ROW / 2 }));

  const nodes: TimelineNode[] = [];
  order.forEach((scholarId, row) => {
    const seen = new Map<string, number>();
    for (const w of lead.get(scholarId)!) {
      const slot = w.year ? String(w.year) : 'nd';
      const n = seen.get(slot) ?? 0;
      seen.set(slot, n + 1);
      const base = w.year ? scale(w.year) : undatedX;
      nodes.push({ id: w.id, x: base + n * 9, y: rows[row].y, row });
    }
  });

  const ticks: Timeline['ticks'] = [];
  for (let y = min; y < pivot - 15; y += 40) ticks.push({ year: y, x: scale(y) }); // stops short of the pivot so its label stays clear
  for (let y = pivot; y <= max; y += 5) ticks.push({ year: y, x: scale(y) });
  return { width: LEFT + PLOT + RIGHT + 30, height: TOP + rows.length * ROW + 10, left: LEFT, rows, ticks, undatedX, nodes };
}

export const THEME_ORDER = [
  'Dating and common links',
  'Isnād and transmission',
  'Rijāl and jarḥ wa-taʿdīl',
  'Canonization and collections',
  'Authenticity debate',
  'Legal ḥadīth and sunna',
  'Sīra and maghāzī sources',
  'Shiʿi ḥadīth',
  'General studies of ḥadīth'
] as const;
