/*
  Build-time data access for the narrator biographies (rijal) pages.
  Data is generated by scripts/build-rijal-data.cjs from Dhahabi's al-Kashif.
*/
import { readFileSync } from 'node:fs';
import path from 'node:path';

const DATA_DIR = path.join(process.cwd(), 'src', 'data', 'rijal');

export interface RijalEntry {
  id: number;
  num: string | null;
  name: string;
  nameNorm: string;
  teachers: string | null;
  students: string | null;
  death: string | null;
  symbols: string[];
  stub: number;
  text: string;
}

export interface RijalMeta {
  source: string;
  author: string;
  basedOn: string;
  count: number;
  stubs: number;
  withDeath: number;
  withSymbols: number;
  chunk: number;
  chunks: number;
}

let metaCache: RijalMeta | null = null;

export function loadRijalMeta(): RijalMeta {
  if (!metaCache) {
    metaCache = JSON.parse(readFileSync(path.join(DATA_DIR, 'meta.json'), 'utf8'));
  }
  return metaCache!;
}

const chunkCache = new Map<number, RijalEntry[]>();

export function loadRijalChunk(chunkIndex: number): RijalEntry[] {
  let c = chunkCache.get(chunkIndex);
  if (!c) {
    c = JSON.parse(readFileSync(path.join(DATA_DIR, `chunk-${chunkIndex}.json`), 'utf8')) as RijalEntry[];
    if (chunkCache.size > 4) chunkCache.clear();
    chunkCache.set(chunkIndex, c);
  }
  return c;
}

export function loadRijalEntry(id: number): RijalEntry | null {
  const meta = loadRijalMeta();
  if (id < 1 || id > meta.count) return null;
  const chunk = loadRijalChunk(Math.floor((id - 1) / meta.chunk));
  return chunk[(id - 1) % meta.chunk] ?? null;
}

/* Sigla used by Dhahabi (after Mizzi) for the six books and their ancillary works. */
export const SYMBOL_MAP: Record<string, string> = {
  'خ': 'Ṣaḥīḥ al-Bukhārī',
  'م': 'Ṣaḥīḥ Muslim',
  'د': 'Sunan Abī Dāwūd',
  'ت': 'Jāmiʿ al-Tirmidhī',
  'س': 'Sunan al-Nasāʾī',
  'ق': 'Sunan Ibn Mājah',
  'ع': 'All six books',
  '4': 'The four Sunan',
  'خت': 'Bukhārī (taʿlīq notes)',
  'بخ': 'Bukhārī, al-Adab al-Mufrad',
  'مق': 'Muslim (introduction)',
  'تم': 'Tirmidhī, Shamāʾil',
  'سي': 'Nasāʾī, ʿAmal al-yawm wa-l-layla',
  'كن': 'Nasāʾī, al-Kunā',
  'عس': 'Nasāʾī, Musnad ʿAlī',
  'ص': 'Nasāʾī, Khaṣāʾiṣ ʿAlī',
  'مد': 'Abū Dāwūd, al-Marāsīl',
  'قد': 'Abū Dāwūd, al-Qadar',
  'فق': 'Ibn Mājah, al-Tafsīr'
};

export function symbolLabel(sym: string): string {
  return SYMBOL_MAP[sym] ?? 'Ancillary collection (siglum ' + sym + ')';
}

/* Short form of a name for searching Silsilah chains: first few name words. */
export function searchName(name: string): string {
  return name.split(/\s+/).slice(0, 4).join(' ');
}
