/*
  Helpers for the Silsilah hadith database pages.
  Reads the JSON generated by scripts/build-silsilah-data.cjs.
*/
import { readFileSync } from 'node:fs';
import path from 'node:path';

const DATA_DIR = path.join(process.cwd(), 'src', 'data', 'silsilah');

export interface BookSummary {
  h1: string | null;
  slug: string;
  ordinal: number;
  titleEn: string | null;
  titleAr: string | null;
  count: number;
  pages: number;
  firstNum: string | null;
  lastNum: string | null;
}

export interface CollectionInfo {
  slug: string;
  category: string;
  died: string;
  blurb: string;
  nameEn: string;
  nameAr: string;
  shortEn: string;
  shortAr: string;
  author: string;
  hadithCount: number;
  englishCount: number;
  aiCount: number;
  englishPct: number;
  graders: string[];
  bookCount: number;
  books: BookSummary[];
}

export interface ChapterEntry {
  t: 'ch';
  level: 2 | 3;
  n: string;
  en: string | null;
  ar: string | null;
  introEn: string | null;
  introAr: string | null;
  machine: boolean;
  cont: boolean;
}

export interface HadithEntry {
  t: 'h';
  ref: string | null;
  num: string | null;
  nic: string | null;
  anchor: string;
  titleEn: string | null;
  gradeEn: string | null;
  gradeAr: string | null;
  graderEn: string | null;
  gradesRaw: string | null;
  chainEn: string | null;
  bodyEn: string | null;
  mt: number;
  footEn: string | null;
  chainAr: string | null;
  bodyAr: string | null;
  footAr: string | null;
  tags: string | null;
}

export type Entry = ChapterEntry | HadithEntry;

export interface BookData {
  h1: string | null;
  slug: string;
  ordinal: number;
  titleEn: string | null;
  titleAr: string | null;
  introEn: string | null;
  introAr: string | null;
  count: number;
  pages: Entry[][];
}

let indexCache: { collections: CollectionInfo[] } | null = null;

export function loadIndex(): { collections: CollectionInfo[] } {
  if (!indexCache) {
    indexCache = JSON.parse(readFileSync(path.join(DATA_DIR, 'index.json'), 'utf8'));
  }
  return indexCache!;
}

const bookCache = new Map<string, BookData>();

export function loadBook(collection: string, bookSlug: string): BookData {
  const key = collection + '/' + bookSlug;
  let b = bookCache.get(key);
  if (!b) {
    b = JSON.parse(
      readFileSync(path.join(DATA_DIR, collection, 'book-' + bookSlug + '.json'), 'utf8')
    ) as BookData;
    // keep memory bounded during the static build
    if (bookCache.size > 3) bookCache.clear();
    bookCache.set(key, b);
  }
  return b;
}

export const CATEGORY_ORDER = [
  'The Six Books',
  'Early Collections',
  'Ṣaḥīḥ Compilations',
  'Musnads and Muʿjams',
  'Topical Works'
];

const escapeHtml = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/* Escape, then render the light markup the corpus uses: *emphasis* pairs. */
export function renderRich(text: string | null): string {
  if (!text) return '';
  let out = escapeHtml(text);
  out = out.replace(/\*([^*]+)\*/g, '<em>$1</em>');
  return out;
}

export type GradeTone = 'sound' | 'good' | 'weak' | 'bad' | 'none';

export function gradeTone(gradeEn: string | null): GradeTone {
  if (!gradeEn) return 'none';
  const g = gradeEn.toLowerCase();
  if (g.includes('fabricat') || g.includes('rejected') || g.includes('repudiated') || g.includes('baseless')) return 'bad';
  if (g.includes('weak')) return 'weak';
  if (g.includes('agreed') || g.includes('sound') || g.includes('corroborated')) return 'sound';
  if (g.includes('good') || g.includes('fair')) return 'good';
  if (g.includes('no grade') || g.includes('silent')) return 'none';
  return 'none';
}

/* "A > B > C" or "[Chain 1] A > B [Chain 2] C > D" -> list of chains of narrators */
export function parseChains(chainEn: string | null): string[][] {
  if (!chainEn) return [];
  const parts = chainEn.split(/\[Chain \d+\]/).map((p) => p.trim()).filter(Boolean);
  return parts.map((p) =>
    p.split('>').map((n) => n.trim()).filter(Boolean)
  );
}

export function translationLabel(c: CollectionInfo): { label: string; tone: 'full' | 'partial' | 'none' } {
  if (c.englishPct < 5) return { label: 'Arabic only', tone: 'none' };
  const aiShare = c.englishCount ? c.aiCount / c.englishCount : 0;
  if (aiShare > 0.5) return { label: 'English (largely AI-assisted)', tone: 'partial' };
  if (aiShare > 0.1) return { label: 'English (partly AI-assisted)', tone: 'partial' };
  return { label: 'Full English translation', tone: 'full' };
}

export function fmtCount(n: number): string {
  return n.toLocaleString('en-US');
}
