version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "drafts"
    schedule:
      interval: "weekly"
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "drafts"
    schedule:
      interval: "weekly"
