/**
 * The rate limiter bound in wrangler.jsonc, declared by hand for the same
 * reason as src/turso-env.d.ts: worker-configuration.d.ts is generated by
 * `wrangler types` and has not been regenerated since the binding was added.
 * Optional, because /api/subscribe must still work where it is not bound.
 */
interface RateLimitBindings {
  SUBSCRIBE_LIMITER?: RateLimit;
}

declare namespace Cloudflare {
  interface Env extends RateLimitBindings {}
}

interface Env extends RateLimitBindings {}
