/**
 * The Turso connection secrets, declared by hand.
 *
 * `worker-configuration.d.ts` is generated by `wrangler types` from
 * wrangler.jsonc, and these two are not in wrangler.jsonc on purpose — an auth
 * token in a committed config file is the mistake this avoids. They are set
 * with `wrangler secret put` in production and read from .dev.vars locally, so
 * the generator cannot see them and the types have to be stated here.
 *
 * Declaration merging, not a replacement: this adds to the generated `Env`
 * rather than overriding it, and both shapes are augmented because
 * `cloudflare:workers` types its `env` as `Cloudflare.Env`.
 */
interface TursoSecrets {
  TURSO_DATABASE_URL: string;
  TURSO_AUTH_TOKEN: string;
}

declare namespace Cloudflare {
  interface Env extends TursoSecrets {}
}

interface Env extends TursoSecrets {}
